start_urls = ['https://www.douban.com/group/428942/',
              'https://www.douban.com/group/558802/',
              'https://www.douban.com/group/558292/',
              'https://www.douban.com/group/591716/',
              'https://www.douban.com/group/251101/',
              'https://www.douban.com/group/267688/',
              'https://www.douban.com/group/633599/',
              'https://www.douban.com/group/iroom/',
              'https://www.douban.com/group/558815/',
              'https://www.douban.com/group/558444/',
              'https://www.douban.com/group/442295/',
              'https://www.douban.com/group/521294/',
              'https://www.douban.com/group/332196/',
              'https://www.douban.com/group/491675/',
              'https://www.douban.com/group/499320/',
              'https://www.douban.com/group/538362/',
              'https://www.douban.com/group/545417/',
              'https://www.douban.com/group/558817/',
              'https://www.douban.com/group/592453/',
              'https://www.douban.com/group/178091/',
              'https://www.douban.com/group/467799/',
              'https://www.douban.com/group/zufangsh/',
              'https://www.douban.com/group/583132/',
              'https://www.douban.com/group/637731/',
              'https://www.douban.com/group/581823/',
              'https://www.douban.com/group/343066/',
              'https://www.douban.com/group/SHwoman/',
              'https://www.douban.com/group/pudongzufang/',
              'https://www.douban.com/group/homeatshanghai/',
              'https://www.douban.com/group/zufangshanghai/',
              'https://www.douban.com/group/zufan/',
              'https://www.douban.com/group/511562/',
              'https://www.douban.com/group/557646/',
              'https://www.douban.com/group/changningzufan/',
              'https://www.douban.com/group/558784/',
              'https://www.douban.com/group/558479/',
              'https://www.douban.com/group/549538/',
              'https://www.douban.com/group/shanghaizufang/',
              'https://www.douban.com/group/383972/',
              'https://www.douban.com/group/shzf/',
              ]

start_urlstest = ['https://www.douban.com/group/538362/',
                  'https://www.douban.com/group/592453/',
                  'https://www.douban.com/group/491675/',

                  ]
